# Generated by Django 3.1.5 on 2021-01-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorld', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.TextField(default='owner'),
        ),
    ]
